### ISSUE TITLE
mount faild

### ISSUE THREAD

**Issue by XBCT** [yoichiro/chromeos-filesystem-dropbox#76] opened 2017-06-28 18:43 UTC
![screenshot 2017-06-28 at 21 38 16](https://user-images.githubusercontent.com/29760589/27654396-c725174e-5c4a-11e7-8448-68f4d111305d.png)
![screenshot 2017-06-28 at 21 38 25](https://user-images.githubusercontent.com/29760589/27654395-c6e8ca50-5c4a-11e7-88c9-4cc8eaa41c29.png)
what i am do wrong ? chrome os  59.0.3071.91

**Comment by XBCT** [comment] 2017-06-28 18:44
chrome os

**Comment by yoichiro** [comment] 2017-07-04 00:49
@XBCT Thank you for the feedback. Well, I would like to check the error messages regarding the failing. Could you check the error messages on the DevTools Console panel with the following steps?

https://github.com/yoichiro/chromeos-filesystem-dropbox/wiki/How-to-Capture-the-Console-Log-of-DevTools

I guess that I might know the cause of the error at mounting...

**Comment by yoichiro** [comment] 2017-07-20 11:42
@XBCT Could you reproduce the issue with the latest version?

**Comment by yoichiro** [comment] 2017-07-26 23:41
@XBCT I close this issue because you didn't post any comment.

**Closed by yoichiro** 2017-07-26 23:41 UTC
