### ISSUE TITLE
Failed to mount: authorization page could not be loaded

### ISSUE THREAD

**Issue by codeofdusk** [yoichiro/chromeos-filesystem-dropbox#120] opened 2019-12-26 06:24 UTC
STR:

1. Open Filesystem for Dropbox
2. Select "mount your Dropbox"

Expected behavior: authorization page opens.
Observed behavior: the following error is displayed: "Failed to mount: authorization page could not be loaded".

Running latest app version from Chrome Web Store, Chrome OS version 79.0.3945 on a Pixelbook.

**Comment by schultzter** [comment] 2019-12-28 22:36
Same issue on HP Chromebook 14 Version 79.0.3945.86 (Official Build) (64-bit)

**Comment by schultzter** [comment] 2019-12-28 22:41
Duplicates include #99 #98 and #103

**Comment by yoichiro** [comment] 2020-01-04 13:08
Hi guys, thank you for the reporting. I could confirm this behavior. I'm currently investigating this issue. As workaround, the authorization window will be opened after clicking `mount` button continuously.

**Comment by mherman95** [comment] 2020-01-04 16:30
Thank you.

**Comment by rdcowan** [comment] 2020-01-04 18:30
Thank you so much Yoichiro! Your ChromeOS extension for Dropbox is
EXCELLENT! 

It has been difficult without it working...

 Robert 

 -------Original Message-------

**Comment by rdcowan** [comment] 2020-01-04 18:48
The workaround did not work for me. I still can't access my Dropbox
files from the Files App.

 Robert 

 -------Original Message-------

**Comment by yoichiro** [comment] 2020-01-05 02:53
> The workaround did not work for me. I still can't access my Dropbox files from the Files App.

@rdcowan Thank you for the reporting. Hmm... In my pixelbook, the authorization window was opened sometimes after continuous pressing. However, I know that it is not a right solution. I need to find the reason.

Last night, I investigated this issue. But, I could not get any information to solve this issue, because my ChromeOS returned only the message "authorization page could not be loaded".

I intend to consult Google about this issue after a few days...

**Comment by Falcon124** [comment] 2020-01-05 03:59
Hi Yoichiro,
I tried the "continuous press" method on the "Mount your Dropbox" button along with "Press as often as possible" method but neither worked on my Acer Chromebook (running Chrome OS 79.0.3945.86 (Official Build) (64 bit)).

Thanks for looking into the issue & hopefully it can get resolved soon as I'm keen to get the file system up & running again on this new machine :)

**Comment by rdcowan** [comment] 2020-01-05 04:06
Thank you so much Yoichiro. We all appreciate your efforts and
expertise.

 Robert 

 -------Original Message-------

**Comment by yoichiro** [comment] 2020-01-05 05:21
I have some questions about this issue for all users.

* When did you notice this issue? After Chrome OS version 79? Or, before than the 79?
* Have you been using this app until now? If yes, have this app been worked normally before?

I hope that I can get more information as possible.

**Comment by Falcon124** [comment] 2020-01-05 06:15
The mount process worked fine for me on my previous Chromebook when I first set it up back in December 2018. It kept working fine with the existing mount despite ChromeOS automatically updating to the latest stable version. I have since given that Chromebook to my mother to replace her dead Macbook (she's not using Dropbox).

This new Chromebook I've purchased is running the latest version but has the problem whenever I try to run the Mount process.

I suspect that if a user's Dropbox file system was already mounted, it keeps going OK even with the latest version. The problem appears to only be for those of us configuring new mounts but should work fine on previously mounted Dropbox filesystems.

**Comment by rdcowan** [comment] 2020-01-05 11:06
My problem started before Version 79. Probably 78. I checked my
'Connected Apps' on the Dropbox site and the ChromeOS Files Extension
is not listed.

 Could this be a Dropbox Update Issue? 

 -------Original Message-------

**Comment by mherman95** [comment] 2020-01-05 14:03
My issue was exactly like Falcon's. My old Chromebook still has the extension working just fine but it has been mounted for over a year. I set up a new Chromebook a week before Christmas (I believe version 79) and it has the issues.

Matt Herman
________________________________

**Comment by cface63** [comment] 2020-01-06 17:03
Just got a new chromebook with the update of 79 already installed. Tried multiple times to mount and got the error messages. This makes me believe the update is the culprit.

**Comment by Fatmitch** [comment] 2020-01-08 03:05
also having the same issue, thanks to everyone leaving comments before me, I think the solution is already being worked on. Thank you Yoichiro! Cant wait for the fix.

**Comment by yoichiro** [comment] 2020-01-08 12:18
Thank you for guys' comments! I could recognize the situations.

**Comment by yoichiro** [comment] 2020-01-08 12:55
Currently, I'm investigating why the authorization page can't be loaded.

At least, I have only the error message "Authorization page could not be loaded.". That is, I don't have any other information which can use to solve this issue. Becuase, the "chrome.identity" API returns the error message only. I can't know the actual situation about what was happened in the API process.

But, I have started watching the source code of the Chromium OS. I thought that I might find the cause, if I can find the code which throws the error message.

The error message is defined at the following code:

https://cs.chromium.org/chromium/src/chrome/browser/extensions/api/identity/identity_constants.cc?rcl=cdbdc966d5cf02bef5c555187d06a5199c105de5&l=20

```cpp
const char kPageLoadFailure[] = "Authorization page could not be loaded.";
```

Next, I found the code where the `kPageLoadFailure` string is refered.

https://cs.chromium.org/chromium/src/chrome/browser/extensions/api/identity/identity_launch_web_auth_flow_function.cc?rcl=cdbdc966d5cf02bef5c555187d06a5199c105de5&l=79

```cpp
void IdentityLaunchWebAuthFlowFunction::OnAuthFlowFailure(
    WebAuthFlow::Failure failure) {
  switch (failure) {
    case WebAuthFlow::WINDOW_CLOSED:
      error_ = identity_constants::kUserRejected;
      break;
    case WebAuthFlow::INTERACTION_REQUIRED:
      error_ = identity_constants::kInteractionRequired;
      break;
    case WebAuthFlow::LOAD_FAILED:
      error_ = identity_constants::kPageLoadFailure;
      break;
    default:
      NOTREACHED() << "Unexpected error from web auth flow: " << failure;
      error_ = identity_constants::kInvalidRedirect;
      break;
  }
  SendResponse(false);
  if (auth_flow_)
    auth_flow_.release()->DetachDelegateAndDelete();
  Release();  // Balanced in RunAsync.
}
```

As like the code above, the error message is thrown when the `failure` variable becomes the `WebAuthFlow::LOAD_FAILED` value. Furthermore, I found the code where calls the `OnAuthFlowFailure` function with the `WebAuthFlow::LOAD_FAILED` value.

https://cs.chromium.org/chromium/src/chrome/browser/extensions/api/identity/web_auth_flow.cc?rcl=ee7ea7dcf43928ef64337d8857205fa4bb4b4c5f&l=244

```cpp
void WebAuthFlow::DidFinishNavigation(
    content::NavigationHandle* navigation_handle) {
  bool failed = false;

  if (navigation_handle->GetNetErrorCode() != net::OK) {
    if (navigation_handle->GetURL().spec() == url::kAboutBlankURL) {
      DCHECK_EQ(net::ERR_UNKNOWN_URL_SCHEME,
                navigation_handle->GetNetErrorCode());
    } else {
      failed = true;
      TRACE_EVENT_ASYNC_STEP_PAST1("identity", "WebAuthFlow", this,
                                   "DidFinishNavigationFailure", "error_code",
                                   navigation_handle->GetNetErrorCode());
    }
  } else if (navigation_handle->IsInMainFrame() &&
             navigation_handle->GetResponseHeaders() &&
             navigation_handle->GetResponseHeaders()->response_code() >= 400) {
    failed = true;
    TRACE_EVENT_ASYNC_STEP_PAST1(
        "identity", "WebAuthFlow", this, "DidFinishNavigationFailure",
        "response_code",
        navigation_handle->GetResponseHeaders()->response_code());
  }

  if (failed && delegate_)
    delegate_->OnAuthFlowFailure(LOAD_FAILED);
}
```

By the code above, I know that the error is thrown when the `failed` variable becomes `true`. The conditions are the following:

* `GetNetErrorCode()` is not `net::OK` and `GetURL().spec()` is not `url::kAboutBlankURL`.
* `IsInMainFrame()` is `true`, there is the `GetResponseHeaders()` value, and the `response_code()` is 400 or more.

As the result, I will be able to recognize the actual situation, if I can get the values of `GetNetErrorCode()` and `response_code()`. Fortunately, it seems that these values are the target of the trace logging with `TRACE_EVENT_ASYNC_STEP_PAST1`.

But, unfortunately, I don't know how to get the log output now. I got the system and user logs from the `chrome://net-internals` page, but I could not find those outputs.

Is there someone who know how to watch those trace log output?

**Comment by yoichiro** [comment] 2020-01-13 00:42
When I watched the `chrome://tracing` log, I could find the trace log which was outputed by the `TRACE_EVENT_ASYNC_STEP_PAST1` macro from the following code:

https://cs.chromium.org/chromium/src/chrome/browser/extensions/api/identity/web_auth_flow.cc?rcl=ee7ea7dcf43928ef64337d8857205fa4bb4b4c5f&l=244

`error_code = 18446744073709552000`

![EN32id1UUAA0WET](https://user-images.githubusercontent.com/261787/72227045-5e095000-35db-11ea-9560-780c9b89551c.png)

The error code value was overflowed over the max value (18446744073709551616) of the 64bit unsigned value. I found that the traced values are casted to `int` by some macros, but I don't know why the value was broken. Probably, there is possible that the actual value was lost. That is, I think that I could not the actual error code from the `navigation_handle->GetNetErrorCode()` code.

After investigating the `chrome://tracing`, I also saw other log `chrome://net-export`. I confirmed that the 200 HTTP status code was recorded as the response of the authorization page fetching, but I could not find any other information...

To get the correct error code, I need to build a Chromium OS which has debug codes I add. Last night, I tried to build it, but I could not do it because the build steps might be changed from I tried a few years ago...

**Comment by mherman95** [comment] 2020-01-13 01:15
Hitting the mount button repeatedly like you said before worked for me finally. You just have to do it constantly for like 10-15 seconds. It works just fine for me now.

Matt Herman

________________________________

**Comment by rdcowan** [comment] 2020-01-14 04:57
It took me quite a bit longer (maybe 30 seconds) but mine finally
worked as well. 

Robert 

 -------Original Message-------

**Comment by Falcon124** [comment] 2020-01-14 07:24
Clicking the button for about 30 seconds worked for me too. Every few seconds it would pop up the login window which would disappear soon after. Eventually one stayed open, allowing me to login, enter my 2 Factor Auth code and then approve the link. Huzzah! :)

Meanwhile, thanks to Yoichiro for documenting progress in assessing the issue. It's quite fascinating to follow the process :)

**Comment by mtdeguzis** [comment] 2020-01-14 16:28
Bashing the mount button took me > 1 minute, but I eventually go the page as well.

**Comment by 4maself** [comment] 2020-01-15 16:23
An update for Chrome OS has fixed this issue for me (to build 79.0.3945.123).
Maybe it'll be of use for others too.

**Comment by Robin1j** [comment] 2020-01-26 14:46
Good morning;

I'm having the same problem with failure to mount on a new Asus Chromebook running 79.0.3945. 123.

Pressing the Mount button multiple times (50+) just produced a stream of the error message. 

This will be a very useful tool once I get it running, so please let us know if there is anything we can do to help!

Thanks!

**Comment by MikeCamel** [comment] 2020-01-31 22:35
Pixelbook, running 80.0.3987.67.

Dialog appears sometimes, but then disappears almost immediately.

**Comment by theaulddubliner** [comment] 2020-02-06 18:55
As above, if I pound the mount button the login prompt eventually stays visible and eventually lets me mount.

Using the Google log-in caused the window to close.

**Comment by insomniux** [comment] 2020-02-11 08:46
Here same on Lenovo C340-11. Tried to click 'Mount your Dropbox' for several minutes without succes. All apps are up to date, ChromeOS version 79.0.3945.123.
Strange enough, I've installed it on a Lenovo C330 as well where I managed to mount dropbox after a few clicks.

**Comment by yoichiro** [comment] 2020-02-17 01:53
Finally, I found the cause of this issue. As the result, this issue will be fixed at Chrome 82.

In the Dropbox authentication page (generally, it is called a Login Page), there is a ReCAPTCHA. The ReCAPTCHA uses <iframe>. After creating the <iframe> element for ReCAPTCHA, it tries to access to the following URL:

https://www.google.com/recaptcha/api2/anchor?...

However, the request is rejected at somewhere, and the error code `-3` (this value means "An operation was aborted due to user action") is returned as the value of `navigation_handle->GetNetErrorCode()`. The error code is handled at the `WebAuthFlow::DidFinishNavigation()` in the `web_auth_flow.cc`.

https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/extensions/api/identity/web_auth_flow.cc;l=231?q=WebAuthFlow::DidFinishNavigation&ss=chromium%2Fchromium%2Fsrc&originalUrl=https:%2F%2Fcs.chromium.org%2F

This issue was reported at the following:
https://bugs.chromium.org/p/chromium/issues/detail?id=1049565

Yesterday, I found the additional two lines in the `WebAuthFlow::DidFinishNavigation()`. When I copied the lines to my source code set and rebuild it, I could confirm that this issue is fixed.

https://chromium.googlesource.com/chromium/src/+/f58cea1be5a939fda74b776d91215c9a2b274c8a%5E%21/

Currently, I'm building my Chromium OS with the latest master branch on my PC for final check.

**Comment by rdcowan** [comment] 2020-02-17 01:55
Wonderful! Thanks Yoichiro!

 -------Original Message-------

**Comment by yoichiro** [comment] 2020-02-17 11:05
If you want to use this app as soon as possible, put your star for the following issue!
https://bugs.chromium.org/p/chromium/issues/detail?id=1049565

Thank you for your cooperation.  ⭐️

**Comment by mherman95** [comment] 2020-02-17 11:07
I tried but it says it's closed and won't let me star it.

Matt Herman

________________________________

**Comment by rdcowan** [comment] 2020-02-17 11:13
I was able t 'star' it. You need to click on 'Log In' at the top right
of the screen then click on the star.

I was star #5 

Robert 

 -------Original Message-------

**Comment by Fatmitch** [comment] 2020-02-17 11:19
Awesome work!

**Comment by Falcon124** [comment] 2020-02-17 11:52
Thanks Yoichiro, very much appreciated.

Any chance of addressing the "offline" usage of Dropbox on Chrome? :) :) :) :)

**Comment by yoichiro** [comment] 2020-02-20 22:03
Great news! The fix code will be merged in M81. That is, this issue will be fixed at Chrome 81 without waiting for 82.

https://bugs.chromium.org/p/chromium/issues/detail?id=1049565

**Comment by Falcon124** [comment] 2020-02-20 22:15
Great news, thanks Yoichiro :)

**Comment by caroln3** [comment] 2020-03-25 08:41
I have a Lenovo Yoga C630. I am experiencing the same issue :"Failed to mount. Authorization page failed to load."  Chrome OS Version 80.0.3987.158.

**Comment by RhondaRH** [comment] 2020-04-01 20:03
I have a Lenovo Chromebook. I've checked and everything is up to date.
Version 80.0.3987.162  No matter how many times I click, I still get the error message.

Thank you for your help!

**Comment by Baswat** [comment] 2020-04-06 18:57
It did work after 2 or 3 minutes continuously clicking.  I have an Asus C302C, with Chrome OS Version 79.0.3945.123.
Thanks for your updates!

**Comment by kimptoc** [comment] 2020-04-08 06:35
ChromeOS 81 is here :)  - dropbox mounted!  Many thanks @yoichiro for fixing this for us all.

**Comment by yoichiro** [comment] 2020-04-09 00:49
ChromeOS 81 Stable has been released. I updated it on my Pixelbook, and I tested the FileSystem for Dropbox app to confirm whether the issue has been fixed or not. Finally, I could confirm the issue was fixed! Users can mount Dropbox using the app on ChromeOS 81. 

Thank you for all contributors and users. Ok, I close this issue.

**Closed by yoichiro** 2020-04-09 00:49 UTC
